# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  ui:
    image: ui
    build:
      context: Ui
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: Development
    ports:
      - 3000:3000
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123$
    ports:
    - "3306:3306"
  api:
    image: api
    build:
      context: .
      dockerfile: Source/Cafe/Cafe.Api/Dockerfile
    environment:
      aspnetcore_environment: Development
      ConnectionString__dbContext: Server=db;Database=cafe;User=root;Password=Admin123$
      ASPNETCORE_URLS: "http://0.0.0.0:80"
    command: ["dotnet", "watch", "run", "--project", "Cafe.Api/Cafe.Api.csproj"]
    ports:
      - "0.0.0.0:5001:80"
      - "0.0.0.0:5002:80"
    depends_on:
      - db